
// Api URL

// export const BASE_URL = 'https://528e3d6f.ngrok.io/';
// export const SOCKET_BASE_URL = 'https://4a3dd590.ngrok.io/chat';
export const BASE_URL = 'http://3.17.16.210:3001/';
export const SOCKET_BASE_URL = 'http://3.17.16.210:3002/chat';

// Container

export const CHANGE_CONTAINER = "CHANGE_CONTAINER";
export const SEND_NOTIFICATION = "SEND_NOTIFICATION";

// Authentication

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const CREATE_USER_PROFILE = "CREATE_USER_PROFILE";
export const CREATE_USER_PROFILE_SUCCESS = "CREATE_USER_PROFILE_SUCCESS";
export const CREATE_USER_PROFILE_FAIL = "CREATE_USER_PROFILE_FAIL";
export const UPLOAD_PROFILE_PIC = "UPLOAD_PROFILE_PIC";
export const UPLOAD_PROFILE_PIC_SUCCESS = "UPLOAD_PROFILE_PIC_SUCCESS";
export const UPLOAD_PROFILE_PIC_FAIL = "UPLOAD_PROFILE_PIC_FAIL";

// Profile

export const MY_PROFILE = "MY_PROFILE";
export const MY_PROFILE_SUCCESS = "MY_PROFILE_SUCCESS";
export const MY_PROFILE_FAIL = "MY_PROFILE_FAIL";
export const USERS_PROFILE = "USERS_PROFILE";
export const USERS_PROFILE_SUCCESS = "USERS_PROFILE_SUCCESS";
export const USERS_PROFILE_FAIL = "USERS_PROFILE_FAIL";
export const CHANGE_PRIVACY = "CHANGE_PRIVACY";
export const CHANGE_PRIVACY_SUCCESS = "CHANGE_PRIVACY_SUCCESS";
export const CHANGE_PRIVACY_FAIL = "CHANGE_PRIVACY_FAIL";
export const ADD_SOCIAL_LINK = "ADD_SOCIAL_LINK";
export const ADD_SOCIAL_LINK_SUCCESS = "ADD_SOCIAL_LINK_SUCCESS";
export const ADD_SOCIAL_LINK_FAIL = "ADD_SOCIAL_LINK_FAIL";
export const DELETE_SOCIAL_LINK = "DELETE_SOCIAL_LINK";
export const DELETE_SOCIAL_LINK_SUCCESS = "DELETE_SOCIAL_LINK_SUCCESS";
export const DELETE_SOCIAL_LINK_FAIL = "DELETE_SOCIAL_LINK_FAIL";
export const FOLLOW_SOCIAL_LINK = "FOLLOW_SOCIAL_LINK";
export const FOLLOW_SOCIAL_LINK_SUCCESS = "FOLLOW_SOCIAL_LINK_SUCCESS";
export const FOLLOW_SOCIAL_LINK_FAIL = "FOLLOW_SOCIAL_LINK_FAIL";

// Users

export const USERS = "USERS";
export const USERS_SUCCESS = "USERS_SUCCESS";
export const USERS_FAIL = "USERS_FAIL";
export const USERS_UNAUTHENTICATED = "USERS_UNAUTHENTICATED";
export const REQUEST_USERS = "REQUEST_USERS";
export const REQUEST_USERS_SUCCESS = "REQUEST_USERS_SUCCESS";
export const REQUEST_USERS_FAIL = "REQUEST_USERS_FAIL";
export const REFINE_USERS = "REFINE_USERS";
export const REFINE_USERS_SUCCESS = "REFINE_USERS_SUCCESS";
export const REFINE_USERS_FAIL = "REFINE_USERS_FAIL";

// Conversation

export const CONVERSATION = "CONVERSATION";
export const CONVERSATION_SUCCESS = "CONVERSATION_SUCCESS";
export const CONVERSATION_FAIL = "CONVERSATION_FAIL";
export const CONVERSATION_EMPTY = "CONVERSATION_EMPTY";

// Activities

export const ACCEPT_REQUEST = "ACCEPT_REQUEST";
export const ACCEPT_REQUEST_SUCCESS = "ACCEPT_REQUEST_SUCCESS";
export const ACCEPT_REQUEST_FAIL = "ACCEPT_REQUEST_FAIL";
export const REJECT_REQUEST = "REJECT_REQUEST";
export const REJECT_REQUEST_SUCCESS = "REJECT_REQUEST_SUCCESS";
export const REJECT_REQUEST_FAIL = "REJECT_REQUEST_FAIL";
export const CONNECTIONS = "CONNECTIONS";
export const CONNECTIONS_SUCCESS = "CONNECTIONS_SUCCESS";
export const CONNECTIONS_FAIL = "CONNECTIONS_FAIL";
export const INBOX = "INBOX";
export const INBOX_SUCCESS = "INBOX_SUCCESS";
export const INBOX_FAIL = "INBOX_FAIL";
export const ACTIVITIES = "ACTIVITIES";
export const ACTIVITIES_SUCCESS = "ACTIVITIES_SUCCESS";
export const ACTIVITIES_FAIL = "ACTIVITIES_FAIL";
export const REFINE_CONNECTIONS = "REFINE_CONNECTIONS";
export const REFINE_CONNECTIONS_SUCCESS = "REFINE_CONNECTIONS_SUCCESS";
export const REFINE_CONNECTIONS_FAIL = "REFINE_CONNECTIONS_FAIL";